name: 'buptGym'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '01 17 * * *'

jobs:
  Gym:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: 'Install dependencies'
        run: pip install -r requirements.txt
      - name: 'Start gym'
        env:
          DATA: ${{ secrets.DATA }}
        run: python main.py
